README.md

A minor fix to the readme.md and system.json files to reflect the new release and fix broken links.

4.0.1 - Readme and System.json fixes

---

lang/en.json
lang/sv.json
model/partial/roll-modifiers.html
script/sheet/character.js

Added a new category under Roll Modifiers (Other) and an entry called "Carrying capacity". Modified the encumbrance calculation to include this bonus for the max value

Carrying capacity - Roll Modifier

---

model/tab/gear.html
script/sheet/character.js
style/tab/gear.css

This commit adds buttons to decrement and increment the currencies on
the gear tab of the character sheet. Right-click to do steps of 5.
Decrementing into a negative value will automatically decrement a
more valuable currency if available, or do nothing.

Add buttons to modify the currencies

---

lang/sv.json

This commit updates sv.json to match the latest changes in en.json.

Update Swedish translations

---

model/character.html
model/monster-attack.html
model/monster.html
model/stronghold.html
style/common.css
style/item.css
style/tab/main.css

This adds a few fixes for mistakes or issues created by auto-format of handlebar partials. It also adds fixes for chat card title links and monster-attacks

Minor fixes

---

lang/cs.json

Updated Czech lang

---

src/module/components/travel-actions.js
src/module/forbidden-lands.js
src/module/sheets/actor/party-sheet.js
src/styles/sheets/_party-sheet.scss
src/templates/partial/travel-action.hbs
src/templates/party.hbs
static/template.json

- Journal Links now only visible if not broken. <- @maxstar
- template now contains what was previously relegated to flags:
- members: the actors dragged onto the sheet.
- travel: the various categories and ids of the actors in each category.

♻️ Party-Sheet: Merge pull request #62 from aMediocreDad/dev

---

src/module/components/dice-roller.js
src/module/forbidden-lands.js
src/module/sheets/actor/character.js
src/templates/chat/roll.hbs

Added push roll button to chat cards.

✨ Push Roll on Chat Cards: Merge pull request #62 from aMediocreDad/dev

---

.editorconfig
.prettierrc.json

the proposal here is that the scss files should be indented by spaces, motivating the need for many levels of indentation.

chore(editorconfig): Added new rule for scss in editorconfig

---

src/module/sheets/actor/party-sheet.js

see https://github.com/maxstar/forbidden-lands-party-sheet/pull/8

🐛 fix drag and drop in party-sheet for firefox

---

src/styles/components/_character-generator.scss
src/styles/system/_main.scss
src/templates/character-generator.hbs
src/templates/partial/list.hbs

This is just a proof of concept, I accept suggestions to improve the formation of the fields.

feat(character generator): style for new feature

---

src/module/system/entities.js
src/styles/components/_character-generator.scss
src/styles/system/_main.scss
src/templates/party.hbs

This fixes #93 🔧 
Fixed line height in character generator, and journal sheet title.
AFixed party sheet avatar img, and set default to the fbl sun. Also fixed editor height in party sheet.

🐛 Several fixes to sheets

---

src/module/components/character-generator/character-converter.js

Character generator no longer applies attributes after the last update.
Signed-off-by: aMediocreDad <amediocredad@outlook.com>

🐛 Fixes #115

---

.eslintrc.json
package-lock.json
package.json
src/module/forbidden-lands.js
src/module/hooks/message-system.js
src/module/system/settings.js
src/module/utils/semver-compare.js
static/assets/messages/messages.jsonc
tests/utils-tests/semver-compare.test.js

This feature adds a messaging system that takes a json/jsonc file and outputs either a prompt or a chatmessage (not implemented).
This will be used to disseminate information to system users, like the readiness for upcoming Foundry 0.8.

✨ Message System

---

src/module/components/character-generator/character-generator.js
src/module/hooks/message-system.js
src/module/system/settings.js
src/styles/sheets/tab/_combat.scss
src/styles/system/_main.scss
src/styles/utils/_tab-button.scss
src/templates/tab/combat.hbs

Various fixes to logical errors.
Added critical injury heal time to character sheet critical injury section. Fixes #112.

✨ 5.3.5 Release Fixes

---

.editorconfig
.env
.github/workflows/release.yml
.gitignore
CHANGELOG.md
CONTRIBUTING.md
LICENSE
README.md
gulpfile.js
package-lock.json
package.json

This Pull Request brings a new revised Github Actions workflow for releases, along with several fixes to documentation.

🏗️ Improved CI process and docs

---

.github/workflows/release.yml
package-lock.json
package.json
src/module/components/roll-engine/engine.js
src/module/forbidden-lands.js
src/module/sheets/actor/character.js
src/module/system/config.js
src/module/system/entities.js
src/styles/sheets/_character.scss
src/styles/system/_foundry-overrides.scss
src/templates/character.hbs
src/templates/limited-character.hbs
src/templates/monster.hbs
src/templates/party.hbs

This PR contains a bag of fixes that have accumulated, either from reports on Discord or self-discovered.
Also contains one dependency update to resolve a Dependency alert.

🐛 Various minor fixes

---

static/lang/en.json

Fix Aritfact Typo

---

jsconfig.json
rollup.config.js
src/forbidden-lands.js
src/forbidden-lands.scss
src/journal/adventure-sites/adventure-site-generator.js
src/journal/adventure-sites/adventure-site-sheet.js
src/journal/adventure-sites/styles/index.scss
src/journal/adventure-sites/templates/adventure-site-sheet.hbs
src/journal/journal-document.js
src/legacy-styles/components/_editor-override.scss
src/legacy-styles/system/_foundry-overrides.scss
src/system/core/config.js
src/system/core/handlebars.js
src/system/core/sheets.js

This adds support for adventure site sheets used in the official modules.

✨ Adventure Site Sheet

---

static/assets/datasets/chargen/dataset.json

Fix: :bug: Chargen minstrel event 'Enlisted' missing gear

---

src/item/armor/templates/main-tab.hbs
src/item/weapon/templates/main-tab.hbs
src/system/core/foundry-overrides.js

Feat: :sparkles: TinyMCE editor for Weapon and Armor 'feature' field

---

README.md

Docs: :books: Update Readme to include DragnTransfer compatibility

---

src/legacy-styles/system/_foundry-overrides.scss

(#254) Fix: Audio Playlists controls, no active indication

---

manifests/v10/system.json
src/actor/character/character-sheet.js
src/actor/character/templates/character-sheet.hbs
src/actor/character/templates/npc-sheet.hbs
src/actor/monster/templates/monster-sheet.hbs
src/actor/stronghold/templates/stronghold-sheet.hbs
src/components/message-system.js
src/components/sheet-config-modal.hbs
src/legacy-styles/components/_dialog.scss
src/legacy-styles/components/_editor-override.scss
src/legacy-styles/sheets/_character.scss
src/legacy-styles/sheets/_item.scss
src/legacy-styles/sheets/_monster.scss
src/legacy-styles/sheets/_stronghold.scss
src/legacy-styles/system/_foundry-overrides.scss
src/legacy-styles/system/_main.scss
src/utils/sheet-config.js
static/assets/messages/messages.jsonc

- fix: 🐛 Style fixes to sheets, editor
- fix: 🐛 Fix charactersheet config
- fix: 🐛 Update manifest, add message

Fix: Last v10 fixes

---

README.md
src/actor/actor-document.js
src/actor/actor-sheet.js
src/actor/character/character-sheet.js
src/actor/monster/monster-sheet.js
src/actor/party/party-sheet.js
src/actor/stronghold/stronghold-sheet.js
src/actor/stronghold/templates/sheet-tabs/building-tab.hbs
src/components/roll-engine/engine.js
src/components/roll-engine/templates/roll.hbs
src/item/item-sheet.js
src/legacy-styles/system/_foundry-overrides.scss
src/system/core/config.js

- fix: 🐛 Incorrect owner chech for push button visibility
- fix: 🐛 Improve scene thumbnails in sidebar
- fix: 🐛 Enrich item fields
- fix: 🐛 Enrich Actor Fields

Fix: V10 module fixes

---

src/item/item-sheet.js
src/legacy-styles/components/_editor-override.scss

The new version 10.0.3 has a bug preventing me from adding and deleting modification from talent documents.
Accessing getData() is a async function but is used syncron.

Fix a Bug adding or deleting a modification

---

src/system/core/config.js
static/assets/datasets/chargen/dataset-de.json

I add a new char gen dataset in german language and insert it into the config.js

Add german dataset for chargen

---

src/actor/actor-document.js

Fix: Not rolling arrow dice on ranged weapons

---

src/components/item-chatcard.hbs

Fix; Render armor feature correctly

---

src/actor/actor-sheet.js
src/components/modifiers-component.hbs
src/item/armor/templates/main-tab.hbs
static/lang/en.json
static/template.json

Fix: Artifact die on total armor roll

---

src/item/item-document.js

Fix: Roll modifiers on equipped items only

---

src/system/core/hooks.js

Other table on the party sheet table configuration doesn't work
Fixes #310

:bug: Find Prey roll card button not working

---

src/actor/actor-sheet.js

Issue when calculating the encumbrance of a token
Fixes #319

:bug: Encumbrance using max strength

---

src/components/roll-engine/engine.js
src/components/roll-engine/templates/dialog.hbs
src/components/roll-engine/templates/spell-dialog.hbs
src/legacy-styles/components/_dialog.scss

Editable roll title
Fixes #297

:sparkles: Editable roll title

---

src/legacy-styles/sheets/_party-sheet.scss
src/legacy-styles/utils/_functions.scss

CSS issue ? On different tab
Fixes #318

:bug: Party sheet action list dynamic size

---

src/journal/adventure-sites/templates/adventure-site-sheet.hbs
static/lang/de.json
static/lang/en.json

- Add i18n key for "add room" in Adventure Site Sheet
- Translate i18n ley "ATTACK.USE_STRENGTH to german

I18n - new translation key in template

---

src/actor/character/character-sheet.js
src/actor/character/templates/character-sheet.hbs
src/actor/character/templates/npc-sheet.hbs
src/actor/character/templates/sheet-tabs/bio-tab.hbs

:sparkles: Add reputation roll

---

src/actor/_shared-template-tabs/gear-tab.hbs
src/legacy-styles/sheets/tab/_gear.scss
src/system/core/handlebars.js
static/lang/en.json

:sparkles: Count items in gear tab

---

src/journal/adventure-sites/adventure-site-sheet.js
src/journal/adventure-sites/templates/adventure-site-sheet.hbs
src/journal/journal-document.js

:bug: Adventure site Journal entries not working correctly

---

src/system/core/fonts.js

Relative font import

---

.changeset/olive-spiders-sip.md
esbuild.config.ts
src/journal/styles/_journal.scss
src/legacy-styles/sheets/_item.scss
src/system/core/foundry-overrides.js

Fix: Broken Editor

---

.changeset/two-vans-peel.md
src/actor/actor-sheet.js
templates/actor/monster/sheet-tabs/combat-tab.hbs

fix: 🐛 Surface Critical Injuries in Monster sheet

---

.changeset/wicked-hotels-camp.md
src/item/item-sheet.js

fix: 🐛 Other Features not enriched

---

lang/fr.json

Update for the Experience dialog modal

FR lang update

---

.changeset/chatty-feet-behave.md
assets/datasets/chargen/dataset.json

Fixes a typo in the formative events for Minstrels

Update dataset.json to fix typo

---

.changeset/smart-walls-join.md
lang/en.json
src/actor/party/party-sheet.js
src/legacy-styles/sheets/_party-sheet.scss
templates/actor/party/components/action-component.hbs
templates/actor/party/components/member-component.hbs

fix: 🐛 Party sheet character and reference links

---

.changeset/fuzzy-mangos-rhyme.md
lang/en.json
src/actor/character/character-sheet.js
src/components/roll-engine/engine.js

fix: 🐛 Consumable roll not decreasing consumable
